import { Inter } from 'next/font/google'
import '@/app/globals.css'
import NavigationBar from '@/components/NavigationBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-color-primary`}>
        <NavigationBar />
        {children}
      </body>
    </html>
  )
}
